'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Sparkles } from 'lucide-react'

export function AiSummaryButton({ campaignId }: { campaignId: string }) {
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [summary, setSummary] = useState('')
  const [error, setError] = useState('')

  async function generate() {
    setLoading(true)
    setError('')
    setSummary('')
    setOpen(true)
    try {
      const res = await fetch('/api/ai/campaign-summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ campaign_id: campaignId }),
      })
      const data = await res.json()
      if (data.error) setError(data.error)
      else setSummary(data.summary)
    } catch {
      setError('Failed to generate summary')
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      <Button variant="outline" size="sm" onClick={generate}>
        <Sparkles className="h-3.5 w-3.5 mr-1.5" />
        AI Summary
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Campaign Summary</DialogTitle>
          </DialogHeader>
          {loading && <p className="text-sm text-gray-500">Generating summary...</p>}
          {error && <p className="text-sm text-red-600">{error}</p>}
          {summary && (
            <div className="prose prose-sm max-w-none">
              <p className="text-sm text-gray-700 leading-relaxed">{summary}</p>
              <p className="text-xs text-gray-400 mt-3">Generated by AI — review before sending to client.</p>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  )
}
